config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<body>
  <div class="banner">
    <h1> Index de mes flats</h1>
  </div>

  <div class="container">
    <% @flats.each do |flat| %>
    <div class="card">
    <%= link_to flat_path(flat) do %>
      <ul class="card-list">
        <li class="card-list-name"><%= flat.name   %></li>
        <li class="card-list-address"><%= flat.address  %></li>
        <li class="card-list-description">Address: <%=  flat.description %></li>
        <li class="card-list-price"><%=  flat.price_per_night %>€</li>
      </ul>
     <% end %>
    </div>
    <% end %>
  </div>
  <%= link_to 'Add your amazing Flat!', new_flat_path, class:"btn-edit" %>
  <%= link_to 'Add your amazing Flat!', new_flat_path, class:"btn-edit-2" %>
  <%= link_to 'Add your amazing Flat!', new_flat_path, class:"btn-edit-3" %>
  <%= link_to 'Add your amazing Flat!', new_flat_path, class:"btn-edit-4" %>
</body>

app/views/flats/new.html.erb
<%= form_for(@flat) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :price_per_night %>
  <%= f.number_field :price_per_night %>
  <%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<body>
  <div>
    <h2><%= @flat.name %></h2>
    <p>Address :</p>
    <p><%= @flat.address %></p>
    <p>Description</p>
    <p><%= @flat.description %></p>
    <p>Price per price_per_night</p>
    <p><%= @flat.price_per_night %>€</p>
  </div>

  <div>
    <%= link_to 'Rent it ' %>
    <%= link_to 'Back', flats_path, class:"btn-back-btn" %>
    <%= link_to 'Edit your Flat', edit_flat_path, class:"btn-edit-btn" %>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>